### ISSUE TITLE
Can submit code to local server and compile

### ISSUE THREAD

**Issue by autonomatt** [LeedsSharp/MazeSharp#1]
Another page on our mvc app that ls#ers can access and submit their code with a name.

**Comment by autonomatt** [comment]
Either can't resubmit code until your off the queue OR resubmit replaces code and moves you to back of queue.

**Comment by nogginbox** [comment]
- [x] Create controller, view models and views for Code Editor Page
- [x] Add code editor window
- [x] Submit compiles code
- [x] Errors shown in editor window
- [x] Successfuly compiled code stored on server to be executed later (class name used as bot name)
- [x] Show class name as player name and namespace as team name
- [x] Solve button not enabled if no code loaded
- [x] Persist code in code window

**Comment by nogginbox** [comment]
Done.
