### ISSUE TITLE
Lock down IMaze for IPlayer

### ISSUE THREAD

**Issue by autonomatt** [LeedsSharp/MazeSharp#5]
In our last session, players where misused either accidentally or intentionally to hack the Maze. This resulted in hardly any IPlayer algorithms getting anywhere near to solving the maze.

Need to improve on that. IPlayer.Move should not be passed an IMaze. Or certain properties on IMaze should be made private.

**Comment by autonomatt** [comment]
Should we maybe have events on IMaze for IPlayer to hook in to?

**Comment by nogginbox** [comment]
The IPlayer should only know which direction it can go next and should only be able to make one move.

One way to do that would be to change the move method's signature:

```
// From this
ICell Move(IMaze maze);

// To something like this:
Direction Move(IList<Direction> availableDirections);
```

Returning a direction stops the player cheating and skipping steps. Passing either a list of directions not blocked, or a really locked down maze stops the user being able to find out stuff they should not know about the maze.

I think sticking with interfaces keeps it simple and event vs interface method ends up being pretty much identical.

**Comment by nogginbox** [comment]
After chat with @autonomatt 

```
Direction Move(ICell currentCell);
```

**Comment by autonomatt** [comment]
That's done. Just need to refactor all the uses in IPlayer implementations.

**Comment by autonomatt** [comment]
JavaScript needs to be modified.
